import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Project Handler",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="flex flex-col h-screen justify-center">
      <h1 className="text-3xl font-bold text-center text-white m-6">
        Welcome to <br /> Project Handler
      </h1>
      <form className="flex flex-col self-center-safe min-w-sm min-h-24 p-8 rounded-md border-2 border-white">
        <div className="mt-6 flex flex-col gap-4">
          <Input type="text" placeholder="Username or Email" />
          <Input type="password" placeholder="Password" />
          <Button className="bg-blue-500 hover:bg-blue-600">Login</Button>
          <Button className="bg-green-500 hover:bg-green-600">Sign In</Button>
        </div>
      </form>
    {/*
          <h1 className="text-3xl font-bold text-center text-white">
        Welcome to <br /> Project Handler
      </h1>
      <main className="row-start-2 flex flex-col items-center gap-8 sm:items-start">
        <div className="w-full max-w-md rounded-xl bg-white p-10 shadow-xl">
          <form className="flex flex-col gap-5">
            <Input type="text" placeholder="Username or Email" />
            <Input type="password" placeholder="Password" />
            <div className="mt-6 flex flex-col gap-4">
              <Button className="bg-blue-500 hover:bg-blue-600">Login</Button>
              <Button className="bg-green-500 hover:bg-green-600">Sign In</Button>
            </div>
          </form>
        </div>
      </main>
      <footer className="row-start-3 flex flex-wrap items-center justify-center gap-6">
        
      </footer>
    */}
    </div>
  );
}

function Input({ type, placeholder }) {
  return (
    <input
      type={type}
      placeholder={placeholder}
      className="rounded-md border border-gray-300 p-4 text-white text-base focus:outline-none focus:ring-2 focus:ring-blue-500"
    />
  );
}

function Button({ children, className }) {
  return (
    <button className={`rounded-md py-3 text-base text-white focus:outline-none ${className}`}>
      {children}
    </button>
  );
}
